version: '3'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
  proxy:
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  database:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
volumes:
  db_volume:
